<?
session_start();  
include('dbconnect.inc');
include('postVars.inc');
?>
<!DOCTYPE html
          PUBLIC
          "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link type="text/css" rel="stylesheet" href="wmu_hostel.css">
<link type="text/css" rel="stylesheet" href="menus.css">
<? include('js_scripts.inc'); ?>
</head>
<body>
<div id="outer">
